apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app1
spec:
  replicas: 2
  selector:
      matchLabels:
        app: appweb1
  template:
    metadata:
      labels:
        app: appweb1
    spec:
      containers:
      - name: appweb1
        image: sockshead/react-img:app1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app2
spec:
  replicas: 2
  selector:
      matchLabels:
        app: appweb2
  template:
    metadata:
      labels:
        app: appweb2
    spec:
      containers:
      - name: appweb2
        image: sockshead/react-img:app2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react5-app
spec:
  replicas: 2
  selector:
      matchLabels:
        app: appweb
  template:
    metadata:
      labels:
        app: appweb
    spec:
      containers:
      - name: appweb
        image: sockshead/react-img:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always  